development:
    meta:
        name: Portfolio
        byline: Dan Nguyen
    controls:
        infiniteScroll: false
    facets:
        on: 
            - keywords
            - rating
    styles: 
        thumb: 
            width: 180
            quality: 65
            strip: true
        thumb_0:
            width: 180
            quality: 65
            strip: true
        thumb_1: 
            width: 380
            quality: 75
            strip: true
        thumb_2:
            width: 580
            quality: 80
            strip: true
        large: 
            width: 1000
            quality: 80
            strip: false
            
        
    source:
        dir: ~/projects/depgal_working/working/testimages 
        subDirs: false
    gallery:
        per_page: 20
        width: 600
        imageViewerWidth: 600
        sortBy: filename
        columns: 
            number: 4
            margin: 5
        images:
            padding: '0 0 0 0'
            border: 0
            borderColor: 0
            marginY: 5
            
    
    
